<a href="https://colab.research.google.com/github/vyenn/ML2024/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.tensor() -- https://docs.pytorch.org/docs/stable/tensors.html

In [45]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
# Get scalar back an Python int -- only works with scalar tensors
print(scalar.item())

tensor(7)
0
7


In [37]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [40]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])
print(MATRIX[1][0])

2
torch.Size([2, 2])
tensor([ 9, 10])
tensor(9)


In [41]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])
3
torch.Size([1, 3, 3])


In [42]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Rabdom tensors

Why random tensors?

They are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with some numbers -> look at data -> update the numbers -> repeat`

In [49]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)

# As we can see below, the entries are drawn from Unif(0,1)
random_tensor

tensor([[0.6475, 0.8552, 0.0746, 0.4249],
        [0.0098, 0.2675, 0.4123, 0.1920],
        [0.3733, 0.1581, 0.5492, 0.9440]])

In [54]:
# Create a random tensor representing an image
random_image_size_tensor = torch.rand(3, 224, 224) # RGB color channels, height, width
random_image_size_tensor

tensor([[[0.3392, 0.3318, 0.6064,  ..., 0.8150, 0.2976, 0.4604],
         [0.8149, 0.3850, 0.2371,  ..., 0.4681, 0.6602, 0.4831],
         [0.6106, 0.7565, 0.3337,  ..., 0.7489, 0.3109, 0.5287],
         ...,
         [0.6592, 0.3678, 0.0894,  ..., 0.4198, 0.4253, 0.5726],
         [0.2325, 0.3607, 0.7730,  ..., 0.6448, 0.3400, 0.0643],
         [0.9560, 0.4845, 0.4423,  ..., 0.8878, 0.2390, 0.5248]],

        [[0.8467, 0.2336, 0.3834,  ..., 0.8653, 0.8005, 0.5255],
         [0.8646, 0.4040, 0.6860,  ..., 0.0884, 0.8420, 0.1502],
         [0.0598, 0.0040, 0.9781,  ..., 0.4910, 0.1792, 0.8792],
         ...,
         [0.6748, 0.7032, 0.7669,  ..., 0.8047, 0.1171, 0.7007],
         [0.7872, 0.8625, 0.4300,  ..., 0.3847, 0.9755, 0.4109],
         [0.8682, 0.3507, 0.3099,  ..., 0.7335, 0.1822, 0.5367]],

        [[0.8189, 0.2641, 0.9738,  ..., 0.3514, 0.5068, 0.0553],
         [0.4231, 0.6550, 0.9322,  ..., 0.0775, 0.6550, 0.6853],
         [0.9489, 0.3310, 0.7384,  ..., 0.0240, 0.0125, 0.

### Zeroes and ones

In [56]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
ones.dtype # data type of entries (they must be the same within a tensor)

torch.float32

### Creating a range of tensors and tensors-like

In [63]:
vector = torch.arange(0,20, 2)
zero_vector = torch.zeros_like(vector)
print(vector)
print(zero_vector)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note:** One of the most frequent errors when using PyTorch are:
1. wrong datatype
2. wrong shape
3. tensors on wrong device

In [65]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32, float16, complex32)
                               device = None, # what device is your tensor on, eg. cpu, cuda
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [69]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [71]:
# Just a quick note that the function Tensor.size() returns its shape so T.size() = T.shape

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition (el-wise)
* Multiplication (el-wise)
* Matrix multiplication

In [104]:
# Matrix multiplication
tensor = torch.arange(1000)

In [111]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 718 µs, sys: 0 ns, total: 718 µs
Wall time: 637 µs


tensor(332833500)

In [110]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(332833500)
CPU times: user 18.9 ms, sys: 2 ms, total: 20.9 ms
Wall time: 21.2 ms


In [119]:
x = torch.tensor([[5,7,1],
                [100,200,5]])
print(x.max(), x.argmax()) # as you can see, argmax works weird with tensors of ndim>1,
                           # since it treats it as if it was of ndim=1

tensor(200) tensor(4)


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - returns a view (**'pointer'**) of an input tensor of certain shape but **shares the memory with the original tensor**
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1-dimensions from a tensor
* Unsqueeze - adds a 1-dimension to a target tensor
* Permute - returns a view of the input with dimension permuted in a certain way

In [142]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [133]:
# Reshape
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [151]:
 # Change the view
 z = x.view(3,3)
 z[1:3,0] = 0
 x

tensor([1, 2, 3, 0, 5, 6, 0, 8, 9])

In [149]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [0, 0, 0, 0],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [0, 0, 0, 0],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

## PyTorch and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor, want in NumPy -> torch.your_tensor.numpy()