<a href="https://colab.research.google.com/github/vyenn/ML2024/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using torch.tensor() -- https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
# Get scalar back an Python int -- only works with scalar tensors
print(scalar.item())

tensor(7)
0
7


In [ ]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])
print(MATRIX[1][0])

2
torch.Size([2, 2])
tensor([ 9, 10])
tensor(9)


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])
3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

### Rabdom tensors

Why random tensors?

They are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with some numbers -> look at data -> update the numbers -> repeat`

In [ ]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)

# As we can see below, the entries are drawn from Unif(0,1)
random_tensor

tensor([[0.3736, 0.0274, 0.4958, 0.8941],
        [0.9247, 0.5414, 0.1977, 0.3174],
        [0.4363, 0.2776, 0.2352, 0.6884]])

In [ ]:
# Create a random tensor representing an image
random_image_size_tensor = torch.rand(3, 224, 224) # RGB color channels, height, width
random_image_size_tensor

tensor([[[0.6456, 0.7837, 0.6939,  ..., 0.2048, 0.7228, 0.8019],
         [0.8863, 0.2375, 0.4880,  ..., 0.1561, 0.9553, 0.2230],
         [0.6815, 0.0187, 0.7348,  ..., 0.8612, 0.3736, 0.7842],
         ...,
         [0.8048, 0.7281, 0.9014,  ..., 0.5264, 0.4436, 0.3491],
         [0.6126, 0.2679, 0.7675,  ..., 0.5383, 0.7039, 0.1994],
         [0.6803, 0.2285, 0.1274,  ..., 0.1420, 0.9061, 0.9215]],

        [[0.5371, 0.4422, 0.6280,  ..., 0.8285, 0.9043, 0.5893],
         [0.4556, 0.4824, 0.7755,  ..., 0.8259, 0.2956, 0.0870],
         [0.1982, 0.2407, 0.7021,  ..., 0.5852, 0.7433, 0.9800],
         ...,
         [0.5477, 0.1117, 0.2541,  ..., 0.5687, 0.4841, 0.7554],
         [0.9203, 0.4822, 0.1102,  ..., 0.2583, 0.1263, 0.8053],
         [0.0434, 0.5752, 0.1374,  ..., 0.1974, 0.1107, 0.4400]],

        [[0.9051, 0.9651, 0.9658,  ..., 0.9027, 0.8222, 0.8097],
         [0.0465, 0.4060, 0.8441,  ..., 0.3819, 0.9294, 0.6261],
         [0.7440, 0.5270, 0.4989,  ..., 0.1512, 0.3394, 0.

### Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
ones.dtype # data type of entries (they must be the same within a tensor)

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
vector = torch.arange(0,20, 2)
zero_vector = torch.zeros_like(vector)
print(vector)
print(zero_vector)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note:** One of the most frequent errors when using PyTorch are:
1. wrong datatype
2. wrong shape
3. tensors on wrong device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32, float16, complex32)
                               device = None, # what device is your tensor on, eg. cpu, cuda
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
# Just a quick note that the function Tensor.size() returns its shape so T.size() = T.shape

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition (el-wise)
* Multiplication (el-wise)
* Matrix multiplication

In [ ]:
# Matrix multiplication
tensor = torch.arange(1000)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 1.19 ms, total: 1.19 ms
Wall time: 18.7 ms


tensor(332833500)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(332833500)
CPU times: user 17.7 ms, sys: 0 ns, total: 17.7 ms
Wall time: 33.9 ms


In [ ]:
x = torch.tensor([[5,7,1],
                [100,200,5]])
print(x.max(), x.argmax()) # as you can see, argmax works weird with tensors of ndim>1,
                           # since it treats it as if it was of ndim=1

tensor(200) tensor(4)


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - returns a view (**'pointer'**) of an input tensor of certain shape but **shares the memory with the original tensor**
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1-dimensions from a tensor
* Unsqueeze - adds a 1-dimension to a target tensor
* Permute - returns a view of the input with dimension permuted in a certain way

In [ ]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Reshape
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
 # Change the view
 z = x.view(3,3)
 z[1:3,0] = 0
 x

tensor([1, 2, 3, 0, 5, 6, 0, 8, 9])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [0, 0, 0, 0],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [0, 0, 0, 0],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

## Indexing
x[first_dim, second_dim, third_dim], for example x[1:5, 1::2, :]

## PyTorch and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor, want in NumPy -> torch.your_tensor.numpy()

In [ ]:
import torch
import numpy as np

#numpy to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

# Notice that numpy array default data type is float64, whereas for torch tensor is float32.
# So if you want to get float32 you have to manually change the type

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [ ]:
# tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

## Reproducibility (seeding)

In [ ]:
torch.manual_seed(42)
A = torch.rand(2,2)
B = torch.rand(2,2)
A,B

(tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[0.3904, 0.6009],
         [0.2566, 0.7936]]))

## Running tensors and PyTorch objects on the GPUs (and making faster computation)

In Google Colab to enable GPU you go to:<br>
runtime -> change runtime type

In [ ]:
!nvidia-smi

Fri Oct 24 13:40:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU Access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor to GPU (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# The above created a copy of tensor on GPU -- .device attribute if not modifiable

tensor([1, 2, 3], device='cuda:0')

### NumPy only works with the CPU, so you might want to move tensors back to the CPU

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])